import{a as v,i as l,S as L}from"./assets/vendor-06b1bbdf.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();function m(r){return r.map(({tags:t,largeImageURL:a,webformatURL:i,likes:e,views:s,comments:n,downloads:p})=>`
      <li class="gallery"><a href="${a}" class="gallery-link">
      <img src="${i}" alt="${t}" title="" class="picture"/>
      </a>
      <ul class = "img-info">
      <li class = "item-info">Likes<span class = "info-value">${e}</span></li>
      <li class = "item-info">Views<span class = "info-value">${s}</span></li>
      <li class = "item-info">Comments<span class = "info-value">${n}</span></li>
      <li class = "item-info">Downloads<span class = "info-value">${p}</span></li>
      </ul>
      </li>
`).join("")}async function h(r="",t){const a="43223956-11c63a864af473bf01df350b7",i="https://pixabay.com/api/";try{const{data:e}=await v.get(i,{params:{key:a,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:"15",page:t}});return e}catch{l.error({message:"Sorry, there are no images matching your search query. Please try again!"})}}const g=document.querySelector(".search-form"),d=document.querySelector(".gallery-list"),u=document.querySelector(".loader"),o=document.querySelector(".load-btn");let c=1;const y=new L(".gallery-link");let f="";g.addEventListener("submit",b);o.addEventListener("click",A);async function b(r){r.preventDefault(),d.innerHTML="",u.classList.add("isActive"),o.classList.remove("isActive"),f=r.currentTarget.search.value.trim();try{c=1;const t=await h(f,c);t.hits.length?(d.insertAdjacentHTML("beforeend",m(t.hits)),y.refresh(),g.reset(),u.classList.remove("isActive"),o.classList.add("isActive")):(l.error({message:"Sorry, there are no images matching your search query. Please try again!"}),u.classList.remove("isActive")),t.hits.length<15&&(l.info({message:"We're sorry, but you've reached the end of search results."}),o.classList.remove("isActive"))}catch{console.log("error")}}async function A(r){r.preventDefault(),o.classList.remove("isActive"),c+=1;try{const t=await h(f,c);d.insertAdjacentHTML("beforeend",m(t.hits)),y.refresh(),t.totalHits/15<c||t.hits.length<15?l.info({message:"We're sorry, but you've reached the end of search results."}):o.classList.add("isActive");const i=document.querySelector(".gallery").getBoundingClientRect().height;window.scrollBy({left:0,top:i*2,behavior:"smooth"})}catch{console.log(error)}}
//# sourceMappingURL=commonHelpers.js.map
